# Generated by Django 5.1.1 on 2024-09-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_administrador_id_alter_cliente_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_admindisco',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
