# Generated by Django 5.1.1 on 2024-09-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_is_admin_user_is_admindisco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='dar_de_alta',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admindisco',
            field=models.BooleanField(default=False, verbose_name='admin disco'),
        ),
    ]
